POST https://api.github.com/repos/xiaojia21190/zhenhunjie/issues HTTP/1.1
Content-Type: application/json
Authorization: token 7f7916b84b762f6465f16500d93ee6da1c2d9c2c

{
  "title":"测试",
  "body": "关闭"
}


###
GET https://api.github.com/repos/xiaojia21190/zhenhunjie/issues?page=1&per_page=1000&state=open HTTP/1.1
Content-Type: application/json
Authorization: token 7f7916b84b762f6465f16500d93ee6da1c2d9c2c

