# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI2222

on:
    schedule:
        - cron: "0 0 */1 * *"

jobs:
    fetch-top-posts:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - name: Use Node.js
              uses: actions/setup-node@v1
              with:
                  node-version: 12.x
            - name: npm install
              run: npm install --only=prod
              working-directory: .
            - name: fetch
              run: node app.js
              working-directory: .
              # for github app auth
              env:
                  Authorization: ${{ secrets.Authorization }}
